import { useState } from "react";
import { ArrowRight, Sparkles, Wifi } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { api } from "../../api";
export default function AuthPage({ mode, onAuth }) {
  const navigate = useNavigate(), location = useLocation(), register = mode === "register";
  const [form, setForm] = useState({ name: "", email: "", password: "" }), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setError(""); setLoading(true); try { const { data } = await api.post(`/auth/${register ? "register" : "login"}`, form); onAuth(data); navigate(location.state?.returnTo || "/", { replace: true }); } catch (err) { setError(err.response?.data?.message || "Something went wrong."); } finally { setLoading(false); } }
  return <div className="auth-page"><Link to="/" className="brand auth-brand"><span className="brand-mark"><Wifi size={19} /></span><span>Sync<span>Space</span></span></Link><div className="auth-card"><div className="eyebrow"><Sparkles size={14} /> Secure workspace</div><h1>{register ? "Create your workspace identity" : "Welcome back"}</h1><p>{register ? "Create an account and join a room." : "Sign in to continue to your meeting."}</p><form onSubmit={submit}>{register && <label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label>}<label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required minLength={6} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" /></label>{error && <div className="error">{error}</div>}<button disabled={loading} className="btn btn-primary btn-wide">{loading ? "Please wait…" : register ? "Create account" : "Sign in"}<ArrowRight size={16} /></button></form><div className="switch">{register ? "Already have an account?" : "New to SyncSpace?"} <Link to={register ? "/login" : "/register"} state={location.state}>{register ? "Sign in" : "Create one"}</Link></div></div></div>;
}
