import { useEffect, useRef, useState } from "react";
import { Eraser, PenLine, X } from "lucide-react";
export default function Whiteboard({ socket, onClose }) {
  const canvasRef = useRef(null), drawingRef = useRef(false), lastPointRef = useRef(null); const [color, setColor] = useState("#ffffff"), [size, setSize] = useState(3);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d"); function resizeCanvas() { const rect = canvas.getBoundingClientRect(), dpr = window.devicePixelRatio || 1; const old = document.createElement("canvas"); old.width = canvas.width; old.height = canvas.height; if (old.width && old.height) old.getContext("2d").drawImage(canvas, 0, 0); canvas.width = Math.max(1, Math.floor(rect.width * dpr)); canvas.height = Math.max(1, Math.floor(rect.height * dpr)); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); if (old.width && old.height) ctx.drawImage(old, 0, 0, old.width, old.height, 0, 0, rect.width, rect.height); } requestAnimationFrame(resizeCanvas); const observer = new ResizeObserver(resizeCanvas); observer.observe(canvas); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!socket) return; const stroke = (s) => drawStroke(s, false), clear = () => clearCanvas(false); socket.on("whiteboard:stroke", stroke); socket.on("whiteboard:clear", clear); return () => { socket.off("whiteboard:stroke", stroke); socket.off("whiteboard:clear", clear); }; }, [socket]);
  function getPoint(e) { const r = canvasRef.current.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; }
  function drawStroke(stroke, emit = true) { const ctx = canvasRef.current?.getContext("2d"); if (!ctx) return; ctx.save(); ctx.strokeStyle = stroke.color || "#fff"; ctx.lineWidth = stroke.size || 3; ctx.lineCap = "round"; ctx.lineJoin = "round"; ctx.beginPath(); ctx.moveTo(stroke.x1, stroke.y1); ctx.lineTo(stroke.x2, stroke.y2); ctx.stroke(); ctx.restore(); if (emit) socket?.emit("whiteboard:stroke", stroke); }
  function handlePointerDown(e) { drawingRef.current = true; lastPointRef.current = getPoint(e); try { canvasRef.current.setPointerCapture(e.pointerId); } catch {} e.preventDefault(); }
  function handlePointerMove(e) { if (!drawingRef.current) return; const current = getPoint(e), previous = lastPointRef.current; if (!previous) return; drawStroke({ x1: previous.x, y1: previous.y, x2: current.x, y2: current.y, color, size }, true); lastPointRef.current = current; e.preventDefault(); }
  function handlePointerUp(e) { drawingRef.current = false; lastPointRef.current = null; try { canvasRef.current.releasePointerCapture(e.pointerId); } catch {} e.preventDefault(); }
  function clearCanvas(emit = true) { const canvas = canvasRef.current, ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return; const r = canvas.getBoundingClientRect(); ctx.clearRect(0, 0, r.width, r.height); if (emit) socket?.emit("whiteboard:clear"); }
  return <div className="overlay"><div className="whiteboard"><div className="wb-head"><div className="wb-title"><PenLine size={18} /><b>Collaborative Whiteboard</b></div><div className="wb-tools"><label className="color-picker"><span>Color</span><input type="color" value={color} onChange={(e) => setColor(e.target.value)} /></label><label className="brush-size"><span>{size}px</span><input type="range" min="1" max="20" value={size} onChange={(e) => setSize(Number(e.target.value))} /></label><button className="icon-btn" onClick={() => clearCanvas(true)} title="Clear whiteboard"><Eraser size={17} /></button><button className="icon-btn" onClick={onClose} title="Close whiteboard"><X size={18} /></button></div></div><div className="canvas-wrapper"><canvas ref={canvasRef} onPointerDown={handlePointerDown} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onPointerCancel={handlePointerUp} /><div className="canvas-hint">Draw something — everyone in the room will see it.</div></div></div></div>;
}
