import { useState } from "react";
import { ArrowRight, Check, Github, Link as LinkIcon, Mic, MonitorUp, PenLine, PhoneOff, Play, Send, ShieldCheck, Upload, Video, Wifi } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Navbar from "../layout/Navbar";
import { makeRoomId } from "../../utils/auth";
function PreviewTile({ initials, name, large }) { return <div className={`preview-tile ${large ? "large" : ""}`}><div className="person">{initials}</div><span>{name}</span></div>; }
function Feature({ icon, title, text }) { return <div className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>; }
function Step({ n, title, text }) { return <div className="step"><strong>{n}</strong><div><h3>{title}</h3><p>{text}</p></div></div>; }
export default function Landing({ auth }) {
  const navigate = useNavigate(); const [joinValue, setJoinValue] = useState("");
  function createRoom() { navigate(`/room/${makeRoomId()}`); }
  function joinRoom(e) { e.preventDefault(); const value = joinValue.trim(); if (!value) return; try { const url = new URL(value); const match = url.pathname.match(/^\/room\/([^/]+)$/); if (match) return navigate(`/room/${match[1]}`); } catch {} navigate(`/room/${value.replace(/^\/?room\//, "")}`); }
  return <div className="landing"><Navbar auth={auth} /><main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> Real-time collaboration</div><h1>Meet. Share.<br /><em>Build together.</em></h1><p>One secure workspace for video meetings, screen sharing, files, chat and a collaborative whiteboard.</p><div className="hero-actions"><button className="btn btn-primary btn-lg" onClick={createRoom}>Start a meeting <ArrowRight size={18} /></button><a href="#workflow" className="btn btn-ghost btn-lg"><Play size={17} /> See how it works</a></div><form className="join-form" onSubmit={joinRoom}><LinkIcon size={17} /><input value={joinValue} onChange={(e) => setJoinValue(e.target.value)} placeholder="Paste room link or room ID" /><button className="btn btn-secondary" type="submit">Join</button></form></div>
    <div className="hero-visual"><div className="glow" /><div className="meeting-preview"><div className="preview-top"><span><span className="live-dot" /> Live workspace</span><span>•••</span></div><div className="preview-grid"><PreviewTile initials="HV" name="You" large /><PreviewTile initials="AK" name="Aarav" /><PreviewTile initials="RM" name="Riya" /></div><div className="preview-bar"><span className="mini-control active"><Mic size={14} /></span><span className="mini-control"><Video size={14} /></span><span className="mini-control"><MonitorUp size={14} /></span><span className="mini-control danger"><PhoneOff size={14} /></span></div></div></div></section>
    <section className="logo-strip"><span>POWERING MODERN TEAMS</span><b>Northstar</b><b>vertex</b><b>orbit</b><b>luma</b><b>stackly</b></section>
    <section id="features" className="section"><div className="section-heading"><div className="eyebrow">Everything in one room</div><h2>Collaboration without<br /><span>context switching.</span></h2><p>Designed around the way distributed teams actually work.</p></div><div className="feature-grid"><Feature icon={<Video />} title="HD video rooms" text="Low-latency multi-user calls with WebRTC." /><Feature icon={<MonitorUp />} title="Screen sharing" text="Present your screen to everyone in the room." /><Feature icon={<Upload />} title="Secure file drops" text="Client-side AES-GCM encryption before relay." /><Feature icon={<PenLine />} title="Live whiteboard" text="Sketch and brainstorm together in real time." /><Feature icon={<Send />} title="Room chat" text="Keep decisions beside the conversation." /><Feature icon={<ShieldCheck />} title="Security first" text="JWT auth, bcrypt and authenticated signaling." /></div></section>
    <section id="security" className="security-section"><div><div className="eyebrow">Private by design</div><h2>Your meeting is<br /><span>your data.</span></h2><p>Media uses WebRTC peer-to-peer transport whenever possible. Files are encrypted in the browser before relay.</p></div><div className="security-card"><ShieldCheck size={32} /><h3>Defense in depth</h3><p>WebRTC + AES-GCM file encryption + JWT + bcrypt.</p><div className="security-line"><Check size={15} /> Encrypted media transport</div><div className="security-line"><Check size={15} /> Encrypted file payloads</div><div className="security-line"><Check size={15} /> Authenticated signaling</div></div></section>
    <section id="workflow" className="section workflow"><div className="section-heading"><div className="eyebrow">Three simple steps</div><h2>From idea to action<br /><span>in seconds.</span></h2></div><div className="steps"><Step n="01" title="Create a room" text="Start instantly and copy the room link." /><Step n="02" title="Invite people" text="Paste the same room link in another browser or tab." /><Step n="03" title="Collaborate" text="Use video, screen share, chat, files and whiteboard." /></div></section>
  </main><footer><div className="brand"><span className="brand-mark"><Wifi size={17} /></span><span>Sync<span>Space</span></span></div><span>© 2026 SyncSpace. Built for real-time work.</span><Github size={17} /></footer></div>;
}
